# Generated by Django 5.2.11 on 2026-02-09 18:06

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter 10 digit Indian mobile number (e.g., 9876543210)', max_length=20, null=True, validators=[myapp.models.validate_indian_phone]),
        ),
    ]
