# Generated by Django 5.2.11 on 2026-02-09 19:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain', 'Maintain Current')], default='maintain', max_length=20)),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('target_bmi', models.FloatField(blank=True, help_text='Target BMI', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)])),
                ('target_body_fat', models.FloatField(blank=True, help_text='Target body fat percentage', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
                ('goal_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_units', models.CharField(choices=[('metric', 'Metric (cm, kg)'), ('imperial', 'Imperial (ft/in, lbs)')], default='metric', max_length=10)),
                ('measurement_reminders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('height', models.FloatField(help_text='Height in centimeters', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.FloatField(help_text='Weight in kilograms', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('age', models.PositiveIntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender for calculations', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light (1-3 days/week)'), ('moderate', 'Moderate (3-5 days/week)'), ('active', 'Active (6-7 days/week)'), ('very_active', 'Very Active (physical job + exercise)')], default='moderate', help_text='Activity level for TDEE calculation', max_length=20)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('lean_mass', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date_recorded'), name='unique_measurement_per_day')],
            },
        ),
    ]
