# Generated by Django 5.2.11 on 2026-02-20 18:08

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customfood_dailystreak_mealentry_workoutentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='date',
            field=models.DateField(default=myapp.models.get_today_date),
        ),
        migrations.AlterField(
            model_name='workoutentry',
            name='date',
            field=models.DateField(default=myapp.models.get_today_date),
        ),
    ]
