# Generated by Django 5.2.11 on 2026-02-20 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mealentry_date_alter_workoutentry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, unique=True)),
                ('calories', models.IntegerField(help_text='Calories per serving', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('protein', models.FloatField(help_text='Protein in grams per serving', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('carbs', models.FloatField(help_text='Carbs in grams per serving', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('fats', models.FloatField(help_text='Fats in grams per serving', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('serving_size', models.CharField(default='100g', help_text='e.g., 100g, 1 cup, 1 piece', max_length=50)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carbs', 'Carbs'), ('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('beverage', 'Beverages'), ('snack', 'Snacks'), ('dairy', 'Dairy')], default='snack', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'food_name'],
            },
        ),
    ]
