# Generated by Django 5.2.11 on 2026-02-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_presetfood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presetfood',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of ingredients (e.g., chicken, salt, pepper)'),
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(help_text='Ingredient or allergen name (e.g., peanuts, dairy, gluten)', max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild - Causes minor discomfort'), ('moderate', 'Moderate - Causes significant discomfort'), ('severe', 'Severe - Life threatening')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', 'ingredient'],
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
