# Generated by Django 5.2.11 on 2026-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_dailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='List any medical conditions like diabetes, hypertension, etc.', null=True),
        ),
    ]
