# Generated by Django 5.2.11 on 2026-02-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_medical_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility/Yoga'), ('sports', 'Sports'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('running', 'Running'), ('hiit', 'HIIT'), ('other', 'Other')], max_length=50)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True, help_text='e.g., Burns fat, Improves stamina')),
                ('target_goal', models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain', 'Maintain Current')], max_length=20, null=True)),
                ('is_low_impact', models.BooleanField(default=False, help_text='Safe for joint issues/asthma')),
                ('requires_equipment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='presetfood',
            name='is_diabetic_friendly',
            field=models.BooleanField(default=False, help_text='Low sugar/carbs'),
        ),
        migrations.AddField(
            model_name='presetfood',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presetfood',
            name='is_heart_healthy',
            field=models.BooleanField(default=False, help_text='Low sodium/saturated fat'),
        ),
        migrations.AddField(
            model_name='presetfood',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
