# Generated by Django 5.2.11 on 2026-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_presetworkout_presetfood_is_diabetic_friendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetworkout',
            name='body_part',
            field=models.CharField(blank=True, help_text='e.g., Chest, Back, Legs, Cardio', max_length=50),
        ),
        migrations.AlterField(
            model_name='presetworkout',
            name='requires_equipment',
            field=models.BooleanField(default=False),
        ),
    ]
