# Generated by Django 5.2.11 on 2026-02-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_presetworkout_body_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutentry',
            name='body_part',
            field=models.CharField(blank=True, help_text='e.g., Chest, Back, Legs', max_length=50),
        ),
    ]
