# Generated by Django 5.2.11 on 2026-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutentry',
            name='reps',
            field=models.IntegerField(blank=True, help_text='Number of repetitions', null=True),
        ),
    ]
