# Generated by Django 5.2.11 on 2026-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_workoutentry_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutentry',
            name='sets',
            field=models.IntegerField(blank=True, help_text='Number of sets', null=True),
        ),
    ]
