# Generated by Django 5.2.11 on 2026-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_badge_gamificationprofile_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetfood',
            name='avoid_for',
            field=models.TextField(blank=True, default='', help_text='Comma-separated conditions this should be avoided for (e.g., hypertension)'),
        ),
        migrations.AddField(
            model_name='presetfood',
            name='suitable_for',
            field=models.TextField(blank=True, default='', help_text='Comma-separated conditions this is good for (e.g., diabetes, PCOS)'),
        ),
        migrations.AddField(
            model_name='presetworkout',
            name='avoid_for',
            field=models.TextField(blank=True, default='', help_text='Comma-separated conditions this should be avoided for (e.g., asthma, knee injury)'),
        ),
        migrations.AddField(
            model_name='presetworkout',
            name='suitable_for',
            field=models.TextField(blank=True, default='', help_text='Comma-separated conditions this is good for (e.g., weight loss, strength)'),
        ),
    ]
