# Generated by Django 5.2.11 on 2026-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_presetfood_avoid_for_presetfood_suitable_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Designates whether this user is banned from the application.'),
        ),
    ]
